<?php
/**
 * Template: handler.tpl.php
 * Variables injected by Generator: TableDef $table
 */

$pk       = $table->pk;
$tbl      = $table->table;
$insert   = $table->insertableColumns();   // ColumnDef[]
$update   = $table->updatableColumns();    // ColumnDef[]
$enums    = $table->enums;
$fkOut    = $table->fkOut;
$fkIn     = $table->fkIn;

$insertNames = array_map(fn($c) => $c->name, $insert);
$updateNames = array_map(fn($c) => $c->name, $update);

// ---- Closures (not named functions — safe to re-include per table) ----------

$buildValidation = function(array $rules): string {
    $lines = [];
    foreach ($rules as $r) {
        $col = $r['col'];
        if (!$r['nullable']) {
            $lines[] = "    if (!array_key_exists('{$col}', \$data) || \$data['{$col}'] === null || \$data['{$col}'] === '') {";
            $lines[] = "        \$errors['{$col}'] = 'required';";
            $lines[] = "    }";
        }
        if ($r['enum']) {
            $allowed = "'" . implode("','", $r['enum']) . "'";
            $lines[] = "    if (isset(\$data['{$col}']) && !in_array(\$data['{$col}'], [{$allowed}], true)) {";
            $lines[] = "        \$errors['{$col}'] = 'must be one of: {$allowed}';";
            $lines[] = "    }";
        }
        if (in_array($r['type'], ['int', 'bigint'], true)) {
            $lines[] = "    if (isset(\$data['{$col}']) && \$data['{$col}'] !== null && !ctype_digit((string)\$data['{$col}'])) {";
            $lines[] = "        \$errors['{$col}'] = 'must be an integer';";
            $lines[] = "    }";
        }
    }
    return implode("\n", $lines);
};

// Builds nested-route block as a string array — no heredoc, no brace leaks
$renderNestedHandler = function(string $childTable, object $fk): string {
    $fkCol    = $fk->column;
    $refTable = $fk->refTable;
    $lines    = [];
    $lines[] = "    // GET /{$refTable}/{id}/{$childTable}[?filters]";
    $lines[] = "    if (\$req->method === 'GET' && \$id !== null && \$req->nested() === '{$childTable}') {";
    $lines[] = "        \$filters = array_diff_key(\$req->query, ['page' => 1, 'per_page' => 1]);";
    $lines[] = "        \$page    = max(1, (int)(\$req->query['page'] ?? 1));";
    $lines[] = "        \$perPage = min(100, (int)(\$req->query['per_page'] ?? 20));";
    $lines[] = "        \$offset  = (\$page - 1) * \$perPage;";
    $lines[] = "        \$where   = ['{$fkCol} = ?'];";
    $lines[] = "        \$params  = [\$id];";
    $lines[] = "        foreach (\$filters as \$col => \$val) {";
    $lines[] = "            \$where[]  = \"`{\$col}` = ?\";";
    $lines[] = "            \$params[] = \$val;";
    $lines[] = "        }";
    $lines[] = "        \$whereStr = implode(' AND ', \$where);";
    $lines[] = "        \$count = DB::get()->prepare(\"SELECT COUNT(*) FROM `{$childTable}` WHERE {\$whereStr}\");";
    $lines[] = "        \$count->execute(\$params);";
    $lines[] = "        \$stmt = DB::get()->prepare(\"SELECT * FROM `{$childTable}` WHERE {\$whereStr} LIMIT ? OFFSET ?\");";
    $lines[] = "        \$stmt->execute([...\$params, \$perPage, \$offset]);";
    $lines[] = "        Response::ok([";
    $lines[] = "            'data' => \$stmt->fetchAll(),";
    $lines[] = "            'meta' => ['page' => \$page, 'per_page' => \$perPage, 'total' => (int)\$count->fetchColumn()],";
    $lines[] = "        ]);";
    $lines[] = "    }";
    return implode("\n", $lines);
};

// Assemble nested handler blocks
$nestedHandlers = '';
foreach ($fkIn as $childTable => $fkDefs) {
    foreach ($fkDefs as $fk) {
        $nestedHandlers .= $renderNestedHandler($childTable, $fk) . "\n\n";
    }
}

// Build validation rule arrays
$insertRules = array_map(fn($c) => [
    'col'      => $c->name,
    'type'     => $c->type,
    'nullable' => $c->nullable,
    'enum'     => $enums[$c->name] ?? null,
], $insert);

$updateRules = array_map(fn($c) => [
    'col'      => $c->name,
    'type'     => $c->type,
    'nullable' => $c->nullable,
    'enum'     => $enums[$c->name] ?? null,
], $update);

$insertValidation = $buildValidation($insertRules);
$updateValidation = $buildValidation($updateRules);

// SQL fragments — computed once here, echoed into the generated file
$insertColsSql      = '`' . implode('`, `', $insertNames) . '`';
$insertPlaceholders = implode(', ', array_fill(0, count($insertNames), '?'));
$updateSetSql       = implode(', ', array_map(fn($c) => "`{$c}` = ?", $updateNames));

// var_export produces a valid PHP array literal for the generated file
$insertNamesExported = var_export($insertNames, true);
$updateNamesExported = var_export($updateNames, true);
?>
<?php echo "<?php\n" ?>

declare(strict_types=1);

/**
 * Handler: <?= $tbl ?>

 * Generated by CRUDify API — do not edit by hand.
 *
 * Routes:
 *   GET    /<?= $tbl ?>             list (paginated, filterable)
 *   GET    /<?= $tbl ?>/{id}        single record
<?php foreach ($fkIn as $childTable => $fkDefs): foreach ($fkDefs as $fk): ?>
 *   GET    /<?= $tbl ?>/{id}/<?= $childTable ?>   nested (<?= $fk->column ?>)
<?php endforeach; endforeach; ?>
 *   POST   /<?= $tbl ?>             create
 *   PUT    /<?= $tbl ?>/{id}        update
 *   DELETE /<?= $tbl ?>/{id}        delete
 */

function <?= $tbl ?>_validate_insert(array $data): array
{
    $errors = [];
<?= $insertValidation ?>

    return $errors;
}

function <?= $tbl ?>_validate_update(array $data): array
{
    $errors = [];
<?= $updateValidation ?>

    return $errors;
}

function <?= $tbl ?>_handle(Request $req): void
{
    $db = DB::get();
    $id = $req->id();

<?= $nestedHandlers ?>
    // GET /<?= $tbl ?>/{id}  — single record
    if ($req->method === 'GET' && $id !== null && $req->nested() === null) {
        $stmt = $db->prepare("SELECT * FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ? LIMIT 1");
        $stmt->execute([$id]);
        $row = $stmt->fetch();
        if (!$row) Response::notFound('<?= ucfirst($tbl) ?> not found');
        Response::ok($row);
    }

    // GET /<?= $tbl ?>  — list (filters + pagination)
    if ($req->method === 'GET' && $id === null) {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page']     ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;

        $where  = ['1=1'];
        $params = [];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);

        $count = $db->prepare("SELECT COUNT(*) FROM `<?= $tbl ?>` WHERE {$whereStr}");
        $count->execute($params);

        $stmt = $db->prepare("SELECT * FROM `<?= $tbl ?>` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);

        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => [
                'page'     => $page,
                'per_page' => $perPage,
                'total'    => (int)$count->fetchColumn(),
            ],
        ]);
    }

    // POST /<?= $tbl ?>  — create
    if ($req->method === 'POST' && $id === null) {
        $data   = $req->body;
        $errors = <?= $tbl ?>_validate_insert($data);
        if ($errors) Response::unprocessable($errors);

        $values = array_map(fn($c) => $data[$c] ?? null, <?= $insertNamesExported ?>);
        $stmt   = $db->prepare("INSERT INTO `<?= $tbl ?>` (<?= $insertColsSql ?>) VALUES (<?= $insertPlaceholders ?>)");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ? LIMIT 1");
        $stmt->execute([$db->lastInsertId()]);
        Response::created($stmt->fetch());
    }

    // PUT /<?= $tbl ?>/{id}  — update
    if ($req->method === 'PUT' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('<?= ucfirst($tbl) ?> not found');

        $data   = $req->body;
        $errors = <?= $tbl ?>_validate_update($data);
        if ($errors) Response::unprocessable($errors);

        $values   = array_map(fn($c) => $data[$c] ?? null, <?= $updateNamesExported ?>);
        $values[] = $id;
        $stmt     = $db->prepare("UPDATE `<?= $tbl ?>` SET <?= $updateSetSql ?> WHERE `<?= $pk ?>` = ?");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ? LIMIT 1");
        $stmt->execute([$id]);
        Response::ok($stmt->fetch());
    }

    // DELETE /<?= $tbl ?>/{id}  — delete
    if ($req->method === 'DELETE' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('<?= ucfirst($tbl) ?> not found');

        $stmt = $db->prepare("DELETE FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ?");
        $stmt->execute([$id]);
        Response::noContent();
    }

    Response::error('Method not allowed', 405);
}