<?php

/**
 * Template: model.tpl.php
 * Injected: TableDef $table, string $className
 */

$pk          = $table->pk;
$tbl         = $table->table;
$insert      = $table->insertableColumns();
$update      = $table->updatableColumns();
$enums       = $table->enums;
$fkOut       = $table->fkOut;
$fkIn        = $table->fkIn;
$insertNames = array_map(fn($c) => $c->name, $insert);
$updateNames = array_map(fn($c) => $c->name, $update);

// --- Validation builder (closure — safe on re-include) ---
$buildValidation = function (array $cols) use ($enums, $fkOut): string {
    $lines = [];
    foreach ($cols as $col) {
        $n = $col->name;
        if (!$col->nullable) {
            $lines[] = "        if (!array_key_exists('{$n}', \$data) || \$data['{$n}'] === null || \$data['{$n}'] === '')";
            $lines[] = "            \$e['{$n}'] = 'required';";
        }
        if (isset($enums[$n])) {
            $list = "'" . implode("','", $enums[$n]) . "'";
            $lines[] = "        if (isset(\$data['{$n}']) && !in_array(\$data['{$n}'], [{$list}], true))";
            $lines[] = "            \$e['{$n}'] = 'must be one of: {$list}';";
        }
        if (in_array($col->type, ['int', 'bigint'], true)) {
            $lines[] = "        if (isset(\$data['{$n}']) && \$data['{$n}'] !== null && !ctype_digit((string)\$data['{$n}']))";
            $lines[] = "            \$e['{$n}'] = 'must be integer';";
        }
    }
    return implode("\n", $lines);
};

// --- Relation methods (one per fkIn entry) ---
$buildRelations = function () use ($fkIn, $tbl, $pk): string {
    $out = [];
    foreach ($fkIn as $childTable => $fkDefs) {
        foreach ($fkDefs as $fk) {
            $method = $childTable; // e.g. bookings()
            $out[] = "    /** Related {$childTable} records via {$childTable}.{$fk->column} */";
            $out[] = "    public static function {$method}(int|string \$id, array \$filters = [], int \$page = 1, int \$perPage = 20): array";
            $out[] = "    {";
            $out[] = "        \$offset  = (\$page - 1) * \$perPage;";
            $out[] = "        \$where   = ['{$fk->column} = ?'];";
            $out[] = "        \$params  = [\$id];";
            $out[] = "        foreach (\$filters as \$col => \$val) { \$where[] = \"`{\$col}` = ?\"; \$params[] = \$val; }";
            $out[] = "        \$w = implode(' AND ', \$where);";
            $out[] = "        \$count = DB::get()->prepare(\"SELECT COUNT(*) FROM `{$childTable}` WHERE {\$w}\");";
            $out[] = "        \$count->execute(\$params);";
            $out[] = "        \$stmt = DB::get()->prepare(\"SELECT * FROM `{$childTable}` WHERE {\$w} LIMIT ? OFFSET ?\");";
            $out[] = "        \$stmt->execute([...\$params, \$perPage, \$offset]);";
            $out[] = "        return ['data' => \$stmt->fetchAll(), 'meta' => ['page' => \$page, 'per_page' => \$perPage, 'total' => (int)\$count->fetchColumn()]];";
            $out[] = "    }";
            $out[] = "";
        }
    }
    return implode("\n", $out);
};

$insertValidation = $buildValidation($insert);
$updateValidation = $buildValidation($update);
$relations        = $buildRelations();

$insertColsSql      = '`' . implode('`, `', $insertNames) . '`';
$insertPlaceholders = implode(', ', array_fill(0, count($insertNames), '?'));
$updateSetSql       = implode(', ', array_map(fn($n) => "`{$n}` = ?", $updateNames));
$insertNamesExp     = var_export($insertNames, true);
$updateNamesExp     = var_export($updateNames, true);

// FK doc lines for class docblock
$fkDocs = '';
foreach ($fkOut as $col => $fk) {
    $fkDocs .= " * @fk   {$col} → {$fk->refTable}.{$fk->refColumn}\n";
}
foreach ($fkIn as $childTable => $fkDefs) {
    foreach ($fkDefs as $fk) {
        $fkDocs .= " * @rel  {$childTable}() via {$childTable}.{$fk->column}\n";
    }
}
?>
<?php echo "<?php\n" ?>

declare(strict_types=1);

/**
* Model: <?= $className ?>

* Table: <?= $tbl ?>

* PK: <?= $pk ?>

<?= $fkDocs ?> * Generated by CRUDify — do not edit by hand.
*
* Usage:
* <?= $className ?>::all(['status' => 'active']);
* <?= $className ?>::find($id);
* <?= $className ?>::create([...]);
* <?= $className ?>::update($id, [...]);
* <?= $className ?>::delete($id);
<?php foreach ($fkIn as $childTable => $fkDefs): ?>
    * <?= $className ?>::<?= $childTable ?>($id, ['status' => 'x']);
<?php endforeach; ?>
*/
class <?= $className ?>

{
// -------------------------------------------------------------------------
// Validation
// -------------------------------------------------------------------------

public static function validateInsert(array $data): array
{
$e = [];
<?= $insertValidation ?>

return $e;
}

public static function validateUpdate(array $data): array
{
$e = [];
<?= $updateValidation ?>

return $e;
}

// -------------------------------------------------------------------------
// CRUD
// -------------------------------------------------------------------------

/**
* List records with optional filters and pagination.
* Returns ['data' => [...], 'meta' => ['page', 'per_page', 'total']]
*/
public static function all(array $filters = [], int $page = 1, int $perPage = 20): array
{
$offset = ($page - 1) * $perPage;
$where = ['1=1'];
$params = [];
foreach ($filters as $col => $val) { $where[] = "`{$col}` = ?"; $params[] = $val; }
$w = implode(' AND ', $where);

$count = DB::get()->prepare("SELECT COUNT(*) FROM `<?= $tbl ?>` WHERE {$w}");
$count->execute($params);
$stmt = DB::get()->prepare("SELECT * FROM `<?= $tbl ?>` WHERE {$w} LIMIT ? OFFSET ?");
$stmt->execute([...$params, $perPage, $offset]);

return ['data' => $stmt->fetchAll(), 'meta' => ['page' => $page, 'per_page' => $perPage, 'total' => (int)$count->fetchColumn()]];
}

/** Find one record by PK. Returns array|null. */
public static function find(int|string $id): ?array
{
$stmt = DB::get()->prepare("SELECT * FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ? LIMIT 1");
$stmt->execute([$id]);
return $stmt->fetch() ?: null;
}

/** Find one record or throw RuntimeException. */
public static function findOrFail(int|string $id): array
{
return static::find($id) ?? throw new RuntimeException("<?= $className ?> #{$id} not found");
}

/**
* Create a new record.
* Returns ['data' => [...], 'errors' => [...]] — check errors before using data.
*/
public static function create(array $data): array
{
$errors = static::validateInsert($data);
if ($errors) return ['data' => null, 'errors' => $errors];

$values = array_map(fn($c) => $data[$c] ?? null, <?= $insertNamesExp ?>);
$stmt = DB::get()->prepare("INSERT INTO `<?= $tbl ?>` (<?= $insertColsSql ?>) VALUES (<?= $insertPlaceholders ?>)");
$stmt->execute($values);

return ['data' => static::find(DB::get()->lastInsertId()), 'errors' => []];
}

/**
* Update a record by PK.
* Returns ['data' => [...], 'errors' => [...]] — null data means not found.
*/
public static function update(int|string $id, array $data): array
{
if (!static::find($id)) return ['data' => null, 'errors' => ['id' => 'not found']];

$errors = static::validateUpdate($data);
if ($errors) return ['data' => null, 'errors' => $errors];

$values = array_map(fn($c) => $data[$c] ?? null, <?= $updateNamesExp ?>);
$values[] = $id;
$stmt = DB::get()->prepare("UPDATE `<?= $tbl ?>` SET <?= $updateSetSql ?> WHERE `<?= $pk ?>` = ?");
$stmt->execute($values);

return ['data' => static::find($id), 'errors' => []];
}

/**
* Delete a record by PK.
* Returns true on success, false if not found.
*/
public static function delete(int|string $id): bool
{
if (!static::find($id)) return false;
$stmt = DB::get()->prepare("DELETE FROM `<?= $tbl ?>` WHERE `<?= $pk ?>` = ?");
$stmt->execute([$id]);
return true;
}

// -------------------------------------------------------------------------
// Relations (from fkIn — tables pointing to this one)
// -------------------------------------------------------------------------

<?= $relations ?>
}