<?php

declare(strict_types=1);

/**
 * Handler: bookings
 * Generated by CRUDify API — do not edit by hand.
 *
 * Routes:
 *   GET    /bookings             list (paginated, filterable)
 *   GET    /bookings/{id}        single record
 *   GET    /bookings/{id}/payments   nested (booking_id)
 *   POST   /bookings             create
 *   PUT    /bookings/{id}        update
 *   DELETE /bookings/{id}        delete
 */

function bookings_validate_insert(array $data): array
{
    $errors = [];
    if (!array_key_exists('user_id', $data) || $data['user_id'] === null || $data['user_id'] === '') {
        $errors['user_id'] = 'required';
    }
    if (isset($data['user_id']) && $data['user_id'] !== null && !ctype_digit((string)$data['user_id'])) {
        $errors['user_id'] = 'must be an integer';
    }
    if (!array_key_exists('room_id', $data) || $data['room_id'] === null || $data['room_id'] === '') {
        $errors['room_id'] = 'required';
    }
    if (isset($data['room_id']) && $data['room_id'] !== null && !ctype_digit((string)$data['room_id'])) {
        $errors['room_id'] = 'must be an integer';
    }
    if (!array_key_exists('check_in', $data) || $data['check_in'] === null || $data['check_in'] === '') {
        $errors['check_in'] = 'required';
    }
    if (!array_key_exists('check_out', $data) || $data['check_out'] === null || $data['check_out'] === '') {
        $errors['check_out'] = 'required';
    }
    if (isset($data['status']) && !in_array($data['status'], ['pending','confirmed','cancelled'], true)) {
        $errors['status'] = 'must be one of: 'pending','confirmed','cancelled'';
    }
    return $errors;
}

function bookings_validate_update(array $data): array
{
    $errors = [];
    if (!array_key_exists('user_id', $data) || $data['user_id'] === null || $data['user_id'] === '') {
        $errors['user_id'] = 'required';
    }
    if (isset($data['user_id']) && $data['user_id'] !== null && !ctype_digit((string)$data['user_id'])) {
        $errors['user_id'] = 'must be an integer';
    }
    if (!array_key_exists('room_id', $data) || $data['room_id'] === null || $data['room_id'] === '') {
        $errors['room_id'] = 'required';
    }
    if (isset($data['room_id']) && $data['room_id'] !== null && !ctype_digit((string)$data['room_id'])) {
        $errors['room_id'] = 'must be an integer';
    }
    if (!array_key_exists('check_in', $data) || $data['check_in'] === null || $data['check_in'] === '') {
        $errors['check_in'] = 'required';
    }
    if (!array_key_exists('check_out', $data) || $data['check_out'] === null || $data['check_out'] === '') {
        $errors['check_out'] = 'required';
    }
    if (isset($data['status']) && !in_array($data['status'], ['pending','confirmed','cancelled'], true)) {
        $errors['status'] = 'must be one of: 'pending','confirmed','cancelled'';
    }
    return $errors;
}

function bookings_handle(Request $req): void
{
    $db = DB::get();
    $id = $req->id();

    // GET /bookings/{id}/payments[?filters]
    if ($req->method === 'GET' && $id !== null && $req->nested() === 'payments') {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page'] ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;
        $where   = ['booking_id = ?'];
        $params  = [$id];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);
        $count = DB::get()->prepare("SELECT COUNT(*) FROM `payments` WHERE {$whereStr}");
        $count->execute($params);
        $stmt = DB::get()->prepare("SELECT * FROM `payments` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);
        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => ['page' => $page, 'per_page' => $perPage, 'total' => (int)$count->fetchColumn()],
        ]);
    }

    // GET /bookings/{id}  — single record
    if ($req->method === 'GET' && $id !== null && $req->nested() === null) {
        $stmt = $db->prepare("SELECT * FROM `bookings` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        $row = $stmt->fetch();
        if (!$row) Response::notFound('Bookings not found');
        Response::ok($row);
    }

    // GET /bookings  — list (filters + pagination)
    if ($req->method === 'GET' && $id === null) {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page']     ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;

        $where  = ['1=1'];
        $params = [];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);

        $count = $db->prepare("SELECT COUNT(*) FROM `bookings` WHERE {$whereStr}");
        $count->execute($params);

        $stmt = $db->prepare("SELECT * FROM `bookings` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);

        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => [
                'page'     => $page,
                'per_page' => $perPage,
                'total'    => (int)$count->fetchColumn(),
            ],
        ]);
    }

    // POST /bookings  — create
    if ($req->method === 'POST' && $id === null) {
        $data   = $req->body;
        $errors = bookings_validate_insert($data);
        if ($errors) Response::unprocessable($errors);

        $values = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'user_id',
  1 => 'room_id',
  2 => 'check_in',
  3 => 'check_out',
  4 => 'status',
));
        $stmt   = $db->prepare("INSERT INTO `bookings` (`user_id`, `room_id`, `check_in`, `check_out`, `status`) VALUES (?, ?, ?, ?, ?)");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `bookings` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$db->lastInsertId()]);
        Response::created($stmt->fetch());
    }

    // PUT /bookings/{id}  — update
    if ($req->method === 'PUT' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `bookings` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Bookings not found');

        $data   = $req->body;
        $errors = bookings_validate_update($data);
        if ($errors) Response::unprocessable($errors);

        $values   = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'user_id',
  1 => 'room_id',
  2 => 'check_in',
  3 => 'check_out',
  4 => 'status',
));
        $values[] = $id;
        $stmt     = $db->prepare("UPDATE `bookings` SET `user_id` = ?, `room_id` = ?, `check_in` = ?, `check_out` = ?, `status` = ? WHERE `id` = ?");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `bookings` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        Response::ok($stmt->fetch());
    }

    // DELETE /bookings/{id}  — delete
    if ($req->method === 'DELETE' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `bookings` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Bookings not found');

        $stmt = $db->prepare("DELETE FROM `bookings` WHERE `id` = ?");
        $stmt->execute([$id]);
        Response::noContent();
    }

    Response::error('Method not allowed', 405);
}