<?php

declare(strict_types=1);

/**
 * Model: Employee
 * Table: employee
 * PK: id
 * Generated by CRUDify — do not edit by hand.
 *
 * Usage:
 * Employee::all(['status' => 'active']);
 * Employee::find($id);
 * Employee::create([...]);
 * Employee::update($id, [...]);
 * Employee::delete($id);
 */
class Employee
{
    // -------------------------------------------------------------------------
    // Validation
    // -------------------------------------------------------------------------

    public static function validateInsert(array $data): array
    {
        $e = [];
        if (isset($data['id']) && $data['id'] !== null && !ctype_digit((string)$data['id']))
            $e['id'] = 'must be integer';
        if (!array_key_exists('company_id', $data) || $data['company_id'] === null || $data['company_id'] === '')
            $e['company_id'] = 'required';
        if (isset($data['company_id']) && $data['company_id'] !== null && !ctype_digit((string)$data['company_id']))
            $e['company_id'] = 'must be integer';
        return $e;
    }

    public static function validateUpdate(array $data): array
    {
        $e = [];
        if (!array_key_exists('company_id', $data) || $data['company_id'] === null || $data['company_id'] === '')
            $e['company_id'] = 'required';
        if (isset($data['company_id']) && $data['company_id'] !== null && !ctype_digit((string)$data['company_id']))
            $e['company_id'] = 'must be integer';
        return $e;
    }

// -------------------------------------------------------------------------
// CRUD
// -------------------------------------------------------------------------

    /**
     * List records with optional filters and pagination.
     * Returns ['data' => [...], 'meta' => ['page', 'per_page', 'total']]
     */
    public static function all(array $filters = [], int $page = 1, int $perPage = 20): array
    {
        $offset = ($page - 1) * $perPage;
        $where = ['1=1'];
        $params = [];
        foreach ($filters as $col => $val) {
            $where[] = "`{$col}` = ?";
            $params[] = $val;
        }
        $w = implode(' AND ', $where);

        $count = DB::get()->prepare("SELECT COUNT(*) FROM `employee` WHERE {$w}");
        $count->execute($params);
        $stmt = DB::get()->prepare("SELECT * FROM `employee` WHERE {$w} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);

        return ['data' => $stmt->fetchAll(), 'meta' => ['page' => $page, 'per_page' => $perPage, 'total' => (int)$count->fetchColumn()]];
    }

    /** Find one record by PK. Returns array|null. */
    public static function find(int|string $id): ?array
    {
        $stmt = DB::get()->prepare("SELECT * FROM `employee` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        return $stmt->fetch() ?: null;
    }

    /** Find one record or throw RuntimeException. */
    public static function findOrFail(int|string $id): array
    {
        return static::find($id) ?? throw new RuntimeException("Employee #{$id} not found");
    }

    /**
     * Create a new record.
     * Returns ['data' => [...], 'errors' => [...]] — check errors before using data.
     */
    public static function create(array $data): array
    {
        $errors = static::validateInsert($data);
        if ($errors) return ['data' => null, 'errors' => $errors];

        $values = array_map(fn($c) => $data[$c] ?? null, array(
            0 => 'id',
            1 => 'company_id',
            2 => 'name',
        ));
        $stmt = DB::get()->prepare("INSERT INTO `employee` (`id`, `company_id`, `name`) VALUES (?, ?, ?)");
        $stmt->execute($values);

        return ['data' => static::find(DB::get()->lastInsertId()), 'errors' => []];
    }

    /**
     * Update a record by PK.
     * Returns ['data' => [...], 'errors' => [...]] — null data means not found.
     */
    public static function update(int|string $id, array $data): array
    {
        if (!static::find($id)) return ['data' => null, 'errors' => ['id' => 'not found']];

        $errors = static::validateUpdate($data);
        if ($errors) return ['data' => null, 'errors' => $errors];

        $values = array_map(fn($c) => $data[$c] ?? null, array(
            0 => 'company_id',
            1 => 'name',
        ));
        $values[] = $id;
        $stmt = DB::get()->prepare("UPDATE `employee` SET `company_id` = ?, `name` = ? WHERE `id` = ?");
        $stmt->execute($values);

        return ['data' => static::find($id), 'errors' => []];
    }

    /**
     * Delete a record by PK.
     * Returns true on success, false if not found.
     */
    public static function delete(int|string $id): bool
    {
        if (!static::find($id)) return false;
        $stmt = DB::get()->prepare("DELETE FROM `employee` WHERE `id` = ?");
        $stmt->execute([$id]);
        return true;
    }

    // -------------------------------------------------------------------------
    // Relations (from fkIn — tables pointing to this one)
    // -------------------------------------------------------------------------

}
