<?php

declare(strict_types=1);

/**
 * Handler: payments
 * Generated by CRUDify API — do not edit by hand.
 *
 * Routes:
 *   GET    /payments             list (paginated, filterable)
 *   GET    /payments/{id}        single record
 *   POST   /payments             create
 *   PUT    /payments/{id}        update
 *   DELETE /payments/{id}        delete
 */

function payments_validate_insert(array $data): array
{
    $errors = [];
    if (!array_key_exists('booking_id', $data) || $data['booking_id'] === null || $data['booking_id'] === '') {
        $errors['booking_id'] = 'required';
    }
    if (isset($data['booking_id']) && $data['booking_id'] !== null && !ctype_digit((string)$data['booking_id'])) {
        $errors['booking_id'] = 'must be an integer';
    }
    if (!array_key_exists('amount', $data) || $data['amount'] === null || $data['amount'] === '') {
        $errors['amount'] = 'required';
    }
    if (isset($data['status']) && !in_array($data['status'], ['pending','paid','failed'], true)) {
        $errors['status'] = 'must be one of: 'pending','paid','failed'';
    }
    return $errors;
}

function payments_validate_update(array $data): array
{
    $errors = [];
    if (!array_key_exists('booking_id', $data) || $data['booking_id'] === null || $data['booking_id'] === '') {
        $errors['booking_id'] = 'required';
    }
    if (isset($data['booking_id']) && $data['booking_id'] !== null && !ctype_digit((string)$data['booking_id'])) {
        $errors['booking_id'] = 'must be an integer';
    }
    if (!array_key_exists('amount', $data) || $data['amount'] === null || $data['amount'] === '') {
        $errors['amount'] = 'required';
    }
    if (isset($data['status']) && !in_array($data['status'], ['pending','paid','failed'], true)) {
        $errors['status'] = 'must be one of: 'pending','paid','failed'';
    }
    return $errors;
}

function payments_handle(Request $req): void
{
    $db = DB::get();
    $id = $req->id();

    // GET /payments/{id}  — single record
    if ($req->method === 'GET' && $id !== null && $req->nested() === null) {
        $stmt = $db->prepare("SELECT * FROM `payments` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        $row = $stmt->fetch();
        if (!$row) Response::notFound('Payments not found');
        Response::ok($row);
    }

    // GET /payments  — list (filters + pagination)
    if ($req->method === 'GET' && $id === null) {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page']     ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;

        $where  = ['1=1'];
        $params = [];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);

        $count = $db->prepare("SELECT COUNT(*) FROM `payments` WHERE {$whereStr}");
        $count->execute($params);

        $stmt = $db->prepare("SELECT * FROM `payments` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);

        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => [
                'page'     => $page,
                'per_page' => $perPage,
                'total'    => (int)$count->fetchColumn(),
            ],
        ]);
    }

    // POST /payments  — create
    if ($req->method === 'POST' && $id === null) {
        $data   = $req->body;
        $errors = payments_validate_insert($data);
        if ($errors) Response::unprocessable($errors);

        $values = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'booking_id',
  1 => 'amount',
  2 => 'status',
  3 => 'paid_at',
));
        $stmt   = $db->prepare("INSERT INTO `payments` (`booking_id`, `amount`, `status`, `paid_at`) VALUES (?, ?, ?, ?)");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `payments` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$db->lastInsertId()]);
        Response::created($stmt->fetch());
    }

    // PUT /payments/{id}  — update
    if ($req->method === 'PUT' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `payments` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Payments not found');

        $data   = $req->body;
        $errors = payments_validate_update($data);
        if ($errors) Response::unprocessable($errors);

        $values   = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'booking_id',
  1 => 'amount',
  2 => 'status',
  3 => 'paid_at',
));
        $values[] = $id;
        $stmt     = $db->prepare("UPDATE `payments` SET `booking_id` = ?, `amount` = ?, `status` = ?, `paid_at` = ? WHERE `id` = ?");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `payments` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        Response::ok($stmt->fetch());
    }

    // DELETE /payments/{id}  — delete
    if ($req->method === 'DELETE' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `payments` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Payments not found');

        $stmt = $db->prepare("DELETE FROM `payments` WHERE `id` = ?");
        $stmt->execute([$id]);
        Response::noContent();
    }

    Response::error('Method not allowed', 405);
}