<?php

declare(strict_types=1);

/**
 * Handler: properties
 * Generated by CRUDify API — do not edit by hand.
 *
 * Routes:
 *   GET    /properties             list (paginated, filterable)
 *   GET    /properties/{id}        single record
 *   GET    /properties/{id}/rooms   nested (property_id)
 *   POST   /properties             create
 *   PUT    /properties/{id}        update
 *   DELETE /properties/{id}        delete
 */

function properties_validate_insert(array $data): array
{
    $errors = [];
    if (!array_key_exists('name', $data) || $data['name'] === null || $data['name'] === '') {
        $errors['name'] = 'required';
    }
    return $errors;
}

function properties_validate_update(array $data): array
{
    $errors = [];
    if (!array_key_exists('name', $data) || $data['name'] === null || $data['name'] === '') {
        $errors['name'] = 'required';
    }
    return $errors;
}

function properties_handle(Request $req): void
{
    $db = DB::get();
    $id = $req->id();

    // GET /properties/{id}/rooms[?filters]
    if ($req->method === 'GET' && $id !== null && $req->nested() === 'rooms') {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page'] ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;
        $where   = ['property_id = ?'];
        $params  = [$id];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);
        $count = DB::get()->prepare("SELECT COUNT(*) FROM `rooms` WHERE {$whereStr}");
        $count->execute($params);
        $stmt = DB::get()->prepare("SELECT * FROM `rooms` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);
        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => ['page' => $page, 'per_page' => $perPage, 'total' => (int)$count->fetchColumn()],
        ]);
    }

    // GET /properties/{id}  — single record
    if ($req->method === 'GET' && $id !== null && $req->nested() === null) {
        $stmt = $db->prepare("SELECT * FROM `properties` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        $row = $stmt->fetch();
        if (!$row) Response::notFound('Properties not found');
        Response::ok($row);
    }

    // GET /properties  — list (filters + pagination)
    if ($req->method === 'GET' && $id === null) {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page']     ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;

        $where  = ['1=1'];
        $params = [];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);

        $count = $db->prepare("SELECT COUNT(*) FROM `properties` WHERE {$whereStr}");
        $count->execute($params);

        $stmt = $db->prepare("SELECT * FROM `properties` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);

        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => [
                'page'     => $page,
                'per_page' => $perPage,
                'total'    => (int)$count->fetchColumn(),
            ],
        ]);
    }

    // POST /properties  — create
    if ($req->method === 'POST' && $id === null) {
        $data   = $req->body;
        $errors = properties_validate_insert($data);
        if ($errors) Response::unprocessable($errors);

        $values = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'name',
  1 => 'location',
));
        $stmt   = $db->prepare("INSERT INTO `properties` (`name`, `location`) VALUES (?, ?)");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `properties` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$db->lastInsertId()]);
        Response::created($stmt->fetch());
    }

    // PUT /properties/{id}  — update
    if ($req->method === 'PUT' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `properties` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Properties not found');

        $data   = $req->body;
        $errors = properties_validate_update($data);
        if ($errors) Response::unprocessable($errors);

        $values   = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'name',
  1 => 'location',
));
        $values[] = $id;
        $stmt     = $db->prepare("UPDATE `properties` SET `name` = ?, `location` = ? WHERE `id` = ?");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `properties` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        Response::ok($stmt->fetch());
    }

    // DELETE /properties/{id}  — delete
    if ($req->method === 'DELETE' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `properties` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Properties not found');

        $stmt = $db->prepare("DELETE FROM `properties` WHERE `id` = ?");
        $stmt->execute([$id]);
        Response::noContent();
    }

    Response::error('Method not allowed', 405);
}