<?php

declare(strict_types=1);

/**
 * Handler: rooms
 * Generated by CRUDify API — do not edit by hand.
 *
 * Routes:
 *   GET    /rooms             list (paginated, filterable)
 *   GET    /rooms/{id}        single record
 *   GET    /rooms/{id}/bookings   nested (room_id)
 *   POST   /rooms             create
 *   PUT    /rooms/{id}        update
 *   DELETE /rooms/{id}        delete
 */

function rooms_validate_insert(array $data): array
{
    $errors = [];
    if (!array_key_exists('property_id', $data) || $data['property_id'] === null || $data['property_id'] === '') {
        $errors['property_id'] = 'required';
    }
    if (isset($data['property_id']) && $data['property_id'] !== null && !ctype_digit((string)$data['property_id'])) {
        $errors['property_id'] = 'must be an integer';
    }
    if (!array_key_exists('capacity', $data) || $data['capacity'] === null || $data['capacity'] === '') {
        $errors['capacity'] = 'required';
    }
    if (isset($data['capacity']) && $data['capacity'] !== null && !ctype_digit((string)$data['capacity'])) {
        $errors['capacity'] = 'must be an integer';
    }
    if (!array_key_exists('price', $data) || $data['price'] === null || $data['price'] === '') {
        $errors['price'] = 'required';
    }
    return $errors;
}

function rooms_validate_update(array $data): array
{
    $errors = [];
    if (!array_key_exists('property_id', $data) || $data['property_id'] === null || $data['property_id'] === '') {
        $errors['property_id'] = 'required';
    }
    if (isset($data['property_id']) && $data['property_id'] !== null && !ctype_digit((string)$data['property_id'])) {
        $errors['property_id'] = 'must be an integer';
    }
    if (!array_key_exists('capacity', $data) || $data['capacity'] === null || $data['capacity'] === '') {
        $errors['capacity'] = 'required';
    }
    if (isset($data['capacity']) && $data['capacity'] !== null && !ctype_digit((string)$data['capacity'])) {
        $errors['capacity'] = 'must be an integer';
    }
    if (!array_key_exists('price', $data) || $data['price'] === null || $data['price'] === '') {
        $errors['price'] = 'required';
    }
    return $errors;
}

function rooms_handle(Request $req): void
{
    $db = DB::get();
    $id = $req->id();

    // GET /rooms/{id}/bookings[?filters]
    if ($req->method === 'GET' && $id !== null && $req->nested() === 'bookings') {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page'] ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;
        $where   = ['room_id = ?'];
        $params  = [$id];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);
        $count = DB::get()->prepare("SELECT COUNT(*) FROM `bookings` WHERE {$whereStr}");
        $count->execute($params);
        $stmt = DB::get()->prepare("SELECT * FROM `bookings` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);
        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => ['page' => $page, 'per_page' => $perPage, 'total' => (int)$count->fetchColumn()],
        ]);
    }

    // GET /rooms/{id}  — single record
    if ($req->method === 'GET' && $id !== null && $req->nested() === null) {
        $stmt = $db->prepare("SELECT * FROM `rooms` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        $row = $stmt->fetch();
        if (!$row) Response::notFound('Rooms not found');
        Response::ok($row);
    }

    // GET /rooms  — list (filters + pagination)
    if ($req->method === 'GET' && $id === null) {
        $filters = array_diff_key($req->query, ['page' => 1, 'per_page' => 1]);
        $page    = max(1, (int)($req->query['page']     ?? 1));
        $perPage = min(100, (int)($req->query['per_page'] ?? 20));
        $offset  = ($page - 1) * $perPage;

        $where  = ['1=1'];
        $params = [];
        foreach ($filters as $col => $val) {
            $where[]  = "`{$col}` = ?";
            $params[] = $val;
        }
        $whereStr = implode(' AND ', $where);

        $count = $db->prepare("SELECT COUNT(*) FROM `rooms` WHERE {$whereStr}");
        $count->execute($params);

        $stmt = $db->prepare("SELECT * FROM `rooms` WHERE {$whereStr} LIMIT ? OFFSET ?");
        $stmt->execute([...$params, $perPage, $offset]);

        Response::ok([
            'data' => $stmt->fetchAll(),
            'meta' => [
                'page'     => $page,
                'per_page' => $perPage,
                'total'    => (int)$count->fetchColumn(),
            ],
        ]);
    }

    // POST /rooms  — create
    if ($req->method === 'POST' && $id === null) {
        $data   = $req->body;
        $errors = rooms_validate_insert($data);
        if ($errors) Response::unprocessable($errors);

        $values = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'property_id',
  1 => 'room_number',
  2 => 'capacity',
  3 => 'price',
));
        $stmt   = $db->prepare("INSERT INTO `rooms` (`property_id`, `room_number`, `capacity`, `price`) VALUES (?, ?, ?, ?)");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `rooms` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$db->lastInsertId()]);
        Response::created($stmt->fetch());
    }

    // PUT /rooms/{id}  — update
    if ($req->method === 'PUT' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `rooms` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Rooms not found');

        $data   = $req->body;
        $errors = rooms_validate_update($data);
        if ($errors) Response::unprocessable($errors);

        $values   = array_map(fn($c) => $data[$c] ?? null, array (
  0 => 'property_id',
  1 => 'room_number',
  2 => 'capacity',
  3 => 'price',
));
        $values[] = $id;
        $stmt     = $db->prepare("UPDATE `rooms` SET `property_id` = ?, `room_number` = ?, `capacity` = ?, `price` = ? WHERE `id` = ?");
        $stmt->execute($values);

        $stmt = $db->prepare("SELECT * FROM `rooms` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        Response::ok($stmt->fetch());
    }

    // DELETE /rooms/{id}  — delete
    if ($req->method === 'DELETE' && $id !== null) {
        $stmt = $db->prepare("SELECT 1 FROM `rooms` WHERE `id` = ? LIMIT 1");
        $stmt->execute([$id]);
        if (!$stmt->fetch()) Response::notFound('Rooms not found');

        $stmt = $db->prepare("DELETE FROM `rooms` WHERE `id` = ?");
        $stmt->execute([$id]);
        Response::noContent();
    }

    Response::error('Method not allowed', 405);
}